import React from "react";
import NavBar from "../navbar/NavBar";
import Footer from "../Footer/Footer";
import "./Services.css";
import "font-awesome/css/font-awesome.min.css";

const Services = () => {
  return (
    <>
      <NavBar />
      <div>
        <div className="services-container">
          <h1 className="services-header">Our Services</h1>
          <p className="hero-text">We're here to help your business grow!</p>

          <div className="services-cards">
            <div className="service-card">
              <i class="fa-solid fa-phone service-icon"></i>
              <h2 className="service-card-title">Cold Calling</h2>
              <p className="service-card-text">
                Provides 2 fresh leads per day
              </p>
            </div>

            <div className="service-card">
              <i class="fa-solid fa-desktop service-icon"></i>
              <h2 className="service-card-title">Quality Management</h2>
              <p className="service-card-text">
                Monitor the live calls for the cold callers, and listen to the
                leads generated by them to make sure only the qualified leads
                will be sent to the Acquisition Manager. Leads Management:
                Qualifying the old leads to convert them into warm leads and
                send them to the Acuisition Manager.
              </p>
            </div>

            <div className="service-card">
              <i class="fa-solid fa-file-signature service-icon"></i>
              <h2 className="service-card-title">Acquisition Management</h2>
              <ol className="service-card-text">
                <li>
                  Works on all the leads that came through from The Cold Calling
                  department, and the Leads Manager.
                </li>
                <li>
                  Negotiate pricing and push to get the potential leads under
                  contract with the best possible price to give a good
                  oppurtunity for our clients to join the selling competition
                  after disposing it.
                </li>
              </ol>
            </div>
          </div>
        </div>

        <div className="packages-container">
          <h1 className="packages-header">Our Packages</h1>
          <p className="hero-text">Choose one of our premium packages</p>

          <div className="packages-cards">
            <div className="package-card">
              <h2 className="package-card-title">White Package</h2>
              <h2 className="package-card-price">$1,100/mo (1 Month)</h2>
              <h2 className="package-card-price">$999/mo (3 Months)</h2>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Professional Cold Caller.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Automated Dialer.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Lead Call recordings.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Leads Quality Manager.</span>
              </p>
              <button className="package-button">Choose Package</button>
            </div>

            <div className="package-card">
              <h2 className="package-card-title">Blue Package</h2>
              <h2 className="package-card-price">$1,250/mo (1 Month)</h2>
              <h2 className="package-card-price">$1,150/mo (3 Months)</h2>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Professional Cold Caller.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Automated Dialer.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Lead Call recordings.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Leads Quality Manager.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Acquisition Manager.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>ASANA CRM.</span>
              </p>
              <button className="package-button">Choose Package</button>
            </div>

            <div className="package-card">
              <h2 className="package-card-title">Green Package</h2>
              <h2 className="package-card-price">$1,399/mo (1 Month)</h2>
              <h2 className="package-card-price">$1,250/mo (3 Months)</h2>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Professional Cold Caller.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Automated Dialer.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Lead Call recordings.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Leads Quality Manager.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Acquisition Manager.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>ASANA CRM.</span>
              </p>
              <p className="package-card-benefit">
                <i class="fa-solid fa-check"></i>
                <span>Leads Manager.</span>
              </p>
              <button className="package-button">Choose Package</button>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Services;
