import React from "react";
import NavBar from "../navbar/NavBar";
import Footer from "../Footer/Footer";
import "./Services.css";
import "font-awesome/css/font-awesome.min.css";

const Services = () => {
  return (
    <>
      <NavBar />
      <div>
        <div className="services-container">
          <h1 className="services-header">Our Services</h1>
          <p className="hero-text">We're here to help your business grow!</p>

          <div className="services-cards">
            <div className="service-card">
              <i class="fa-solid fa-phone service-icon"></i>
              <h2 className="service-card-title">Cold Calling</h2>
              <p className="service-card-text">
                Provides 2 fresh leads per day
              </p>
            </div>

            <div className="service-card">
              <i class="fa-solid fa-desktop service-icon"></i>
              <h2 className="service-card-title">Quality Management</h2>
              <p className="service-card-text">
                Monitor the live calls for the cold callers, and listen to the
                leads generated by them to make sure only the qualified leads
                will be sent to the Acquisition Manager. Leads Management:
                Qualifying the old leads to convert them into warm leads and
                send them to the Acuisition Manager.
              </p>
            </div>

            <div className="service-card">
              <i class="fa-solid fa-file-signature service-icon"></i>
              <h2 className="service-card-title">Acquisition Management</h2>
              <ol className="service-card-text">
                <li>
                  Works on all the leads that came through from The Cold Calling
                  department, and the Leads Manager.
                </li>
                <li>
                  Negotiate pricing and push to get the potential leads under
                  contract with the best possible price to give a good
                  oppurtunity for our clients to join the selling competition
                  after disposing it.
                </li>
              </ol>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Services;
